#!/bin/sh

usage(){
	echo >&2 "Usage: $0 [--[no-]sync] [--agents-only] [--no-umount]"
	exit 2
}

clear_agents(){
	echo "$0: clearing gpg-agent" >&2
	#echo "reloadagent" | gpg-connect-agent --no-autostart >/dev/null
	pkill -u "$USER" -HUP gpg-agent

	echo "$0: clearing ssh-agent" >&2
	ssh-add -Dq
}

do_sync(){
	echo "$0: sync" >&2
	sync
}

do_x11(){
	if test -n "$DISPLAY"
	then
		echo "$0: X11 display off" >&2
		xset dpms force suspend
	fi
}

do_umount(){
	test -z "$UID" && UID=$(id -u)
	mount \
		| awk '$5 == "fuse.gocryptfs" && $6 ~ "user_id='"$UID"'[,)]" { print $3 }' \
		| while read m
		do
			echo "$0: unmounting \"$m\"" >&2
			fusermount -u "$m"
		done
}

umount=true
sync=false
case $# in
	0)
		;;
	1)
		case "$1" in
			--sync)
				sync=true
				;;
			--no-umount)
				umount=false
				;;
			--no-sync|--agents-only)
				;;
			*)
				usage
				;;
		esac
		;;
	*)
		usage
		;;
esac

clear_agents
if $sync
then do_sync
fi
if $umount
then do_umount
fi
do_x11
