#!/bin/sh

usage(){
	echo >&2 "Usage: $0 path/to/exe [args...]"
	echo >&2 "- Any arguments that exist will be watched for changes"
	exit 2
}

if test $# -eq 0
then usage
fi
case "$1" in -*) usage ;; esac

printf '%s\n' "$@" | stest -e | entr -rc "$@"
