#!/bin/sh

usage(){
	echo >&2 "Usage: $0 exit-code"
	exit 2
}

if test $# -ne 1 || ! echo "$1" | grep '^[0-9]\+$' >/dev/null
then usage
fi

if test $1 -eq 0
then echo success
elif test $1 -gt 1 && test $1 -lt 126
then echo error $1
elif test $1 -eq 126
then echo command cannot execute
elif test $1 -eq 127
then echo command not found
elif test $1 -eq 128
then echo invalid exit'()' argument
elif test $1 -gt 128 && test $1 -lt 166
then
	sig=$(($1 - 128))
	echo killed by signal $(kill -l | tr ' ' '\n' | sed -n ${sig}p) "($sig)"
else
	echo unknown error $1
fi
