#!/bin/sh

set -e

usage(){
	echo >&2 "Usage: $0 [history-file]"
	exit 2
}

err_exit(){
	echo "$*" >&2
	exit 1
}

case $# in
	1)
		h="$1"
		;;
	0)
		if test -n "$BASH"
		then h=~/.bash_history
		elif test -n "$ZSH_VERSION"
		then h=~/.zsh_history
		else err_exit "$0: unknown shell"
		fi
		;;
	*)
		usage
		;;
esac

if ! test -e "$h"
then err_exit "$0: \"$h\" doesn't exist"
fi

bname="$(basename "$0")"

# once it gets to 7k, drop to 5k

n=$(wc -l "$h" | cut -d' ' -f1)
if test $n -le 7000
then exit 0
fi

echo >&2 "$bname: $n lines in $h, archiving..."
archive_count=$(($n - 5000))

#echo "archiving the first $archive_count lines from $h"
#echo "trimming $h to the last 5000 lines"

head -"$archive_count" "$h" >> "$h.archive"
tail -5000 "$h" | sponge "$h"
