#!/bin/sh

usage(){
	echo >&2 "Usage: $0 [--dry] [-i...] source target"
	exit 2
}

is_flag(){
	echo "$1" | grep -q '^-'
}

echo=
if test "$1" = --dry
then
	echo=echo
	shift
fi

case $# in
	2)
		flags=
		src=$1
		targ=$2
		;;
	3)
		if ! is_flag "$1"
		then usage
		fi
		flags=$1
		src=$2
		targ=$3
		;;
	*)
		usage
		;;
esac

if is_flag "$src" || is_flag "$targ"
then usage
fi

if test -d "$targ"
then link_targ="$targ/$(basename "$src")"
else link_targ="$targ"
fi

$echo mv "$flags" "$src" "$targ"
$echo ln -s "$link_targ" "$src"
