#!/bin/sh

usage(){
	echo "Usage: $0 [-n] [-c] [-e] [grep args]" >&2
	echo "       $0 -l" >&2
	echo "-n: no-op" >&2
	echo "-c: clear the screen after a delay" >&2
	echo "-e: edit" >&2
	echo >&2
	echo "-l: list directories" >&2
	exit 2
}

if test $# -eq 0
then usage
fi

if test "$1" = -l
then
	shift
	if test $# -ne 0
	then usage
	fi

	find ~/.password-store/* -type d | sed 's;.*password-store/;;'
	exit $?
fi

dry=no
clear=no
subcmd="show"
while test $# -gt 1
do
	case "$1" in
		-n)
			if test $dry = yes
			then break # argument for grep
			fi
			dry=yes
			shift
			;;
		-c)
			if test $clear = yes
			then break # argument for grep
			fi
			clear=yes
			shift
			;;
		-e)
			subcmd=edit
			shift
			;;
		--help)
			usage
			;;
		*)
			break
			;;
	esac
done

wait_and_clear(){
	count=30
	while test $count -gt 0
	do
		printf '\x1b[2K%d...\r' "$count"
		count=$(expr $count - 1)
		sleep 1
	done
	clear
}

cd ~/.password-store/
ents=$(find */ ! -type d | sed '/^\./d; s/\.gpg$//; s/\/\//\//' | grep "$@")
if test -z "$ents"
then
	echo >&2 "$0: no matches"
	exit 1
elif test $(echo "$ents" | wc -l) -gt 1
then
	echo >&2 "$0: too many matches:"
	echo >&2 "$ents"
	exit 1
else
	if test $dry = no
	then
		echo "pass $subcmd $ents" >&2
		pass $subcmd "$ents"
		if test $clear = yes
		then wait_and_clear
		fi
	else
		echo "found: $ents"
	fi
fi
