#!/bin/sh

if test $# -eq 0
then
	echo "Usage: $0 [-n] [-C] [grep args]" >&2
	echo "-n: no-op" >&2
	echo "-C: don't clear the screen after a delay" >&2
	exit 2
fi

dry=no
clear=yes
while test $# -gt 1
do
	case "$1" in
		-n)
			if test $dry = yes
			then break # argument for grep
			fi
			dry=yes
			shift
			;;
		-C)
			if test $clear = no
			then break # argument for grep
			fi
			clear=no
			shift
			;;
		*)
			break
			;;
	esac
done

wait_and_clear(){
	count=30
	while test $count -gt 0
	do
		printf '\x1b[2K%d...\r' "$count"
		count=$(expr $count - 1)
		sleep 1
	done
	clear
}

cd ~/.password-store/
ents=$(find */ ! -type d | sed '/^\./d; s/\.gpg$//; s/\/\//\//' | grep "$@")
if test -z "$ents"
then
	echo >&2 "$0: no matches"
	exit 1
elif test $(echo "$ents" | wc -l) -gt 1
then
	echo >&2 "$0: too many matches:"
	echo >&2 "$ents"
	exit 1
else
	if test $dry = no
	then
		echo "pass show $ents"
		pass show "$ents"
		if test $clear = yes
		then wait_and_clear
		fi
	else
		echo "found: $ents"
	fi
fi
