#!/bin/sh

if test $# -ne 0
then
	echo >&2 "Usage: $0"
	exit 2
fi

key_grips=$(
	gpg-connect-agent 'keyinfo --list' /bye |
		awk '$7 == "1" { print $3 }' |
		tr '\n' '|' |
		sed 's/|$//'
)

gpg --with-keygrip --list-keys | grep -E -B5 "$key_grips"
