#!/bin/sh

if test $# -ne 1
then
	echo "Usage: $0 name" >&2
	exit 2
fi

if pass git diff | grep . >/dev/null
then
	echo >&2 "pass repo in modified state, aborting"
	exit 1
fi

name="$1"
f=/dev/shm/pass-gen.$$.txt

trap "rm -f '$f'" EXIT

(
	pass generate "$name" 20 | tail -1 | sed 's/\x1b\[[^m]*m//g'
	echo
) >"$f"

pass git reset --quiet --hard HEAD^

echo "generated, launching ed..."
if ! ed "$f"
then
	q=$?
	echo >&2 "ed aborted, cancelling pass-gen"
	exit $q
fi

pass insert \
	--multiline \
	"$name" \
	< "$f"
