#!/bin/sh

usage(){
	echo "Usage: $0 name" >&2
	echo "Usage: $0 -1 length" >&2
	exit 2
}

cancel(){
	# cancel exit-code desc
	echo >&2 "$2, cancelling pass-gen"
	exit $1
}

generate(){
	if pass git diff | grep . >/dev/null
	then
		echo >&2 "pass repo in modified state, aborting"
		exit 1
	fi

	name="$1"
	f=/dev/shm/pass-gen.$$.txt

	trap "rm -f '$f'" EXIT

	(
		pass generate "$name" 20 | tail -1 | sed 's/\x1b\[[^m]*m//g'
		#    ^~~~~~~~ this may fail, but leave pass with the commit in case
		echo
	) >"$f"

	echo "generated, launching ed..."
	if ! ed "$f"
	then
		q=$?
		cancel $q "ed aborted"
	fi
	if test $(wc -c "$f" | cut -d' ' -f1) -eq 0
	then cancel 1 "empty password file"
	fi

	pass git reset --quiet --hard HEAD^
	pass insert \
		--multiline \
		"$name" \
		< "$f"
}

oneshot(){
	LC_ALL=C tr -dc '[:punct:][:alnum:]' </dev/urandom | head -c "$1"
	echo
}

case $# in
	1)
		if echo "$1" | grep '^-' >/dev/null
		then usage
		fi
		generate "$1"
		;;
	2)
		if test "$1" != -1
		then usage
		fi

		if ! echo "$2" | grep '^[0-9]\+$' >/dev/null
		then usage
		fi

		oneshot "$2"
		;;
	*)
		usage
		;;
esac
