#!/bin/sh

if test $# -eq 0
then
	echo "Usage: $0 [-n] [grep args]" >&2
	echo "-n: no-op" >&2
	exit 2
fi

dry=no
if test $# -ge 2 && test "$1" = -n
then
	dry=yes
	shift
fi

cd ~/.password-store/
ents=$(find */ ! -type d | sed '/^\./d; s/\.gpg$//' | grep "$@")
if test -z "$ents"
then
	echo >&2 "$0: no matches"
	exit 1
elif test $(echo "$ents" | wc -l) -gt 1
then
	echo >&2 "$0: too many matches:"
	echo >&2 "$ents"
	exit 1
else
	if test $dry = no
	then
		echo "pass show $ents"
		pass show "$ents"
	else
		echo "found: $ents"
	fi
fi
