#!/bin/sh

hash=sha256

if test $# -eq 3 && test "$1" = -E
then
	hash="$2"
	shift 2
fi

if test $# -ne 1
then
	echo >&2 "Usage: $0 [-E md5|sha256] fingerprint"
	exit 2
fi

keys(){
	for arg
	do test -f "$arg" && ssh-keygen -f "$arg" -l -E "$hash"
	done
}

{
	keys ~/.ssh/known_hosts
	keys /etc/ssh/ssh_known_hosts
	keys /etc/ssh/ssh_host_*_key.pub
} | grep -F -- "$1"
