#!/bin/sh

set -e

usage(){
	cat >&2 <<!
Usage: $0 [ + | - | t[oggle] | l[ist] | volume-to-set ]
!
	exit 2
}

get_active_dev(){
	# return the first '[on]' device

	while read d
	do
		# ignore master control
		if test "$d" = Master
		then continue
		fi

		contents=$(amixer get "$d")
		if echo "$contents" | grep 'Playback channels' >/dev/null \
			&& echo "$contents" | grep '\[on\]$' >/dev/null
		then
			echo "$d"
			return
		fi
	done <<!
$devices
!

	# none found, try Master
	d=Master
	if amixer get "$d" >/dev/null
	then
		echo "$d"
		return
	fi

	echo >&2 "$0: can't find active device"
	exit 1
}

list(){
	echo "$devices" | while read d
	do
		contents=$(amixer get "$d")

		# playback only:
		if ! echo "$contents" | grep 'Playback channels:' >/dev/null
		then continue
		fi
		if ! echo "$contents" | grep pvolume >/dev/null
		then continue
		fi

		if echo "$contents" | grep '\[on\]$' >/dev/null
		then desc='*'
		else desc='-'
		fi

		echo "$desc $d"
	done
}

vol_get(){
	amixer get $dev_default | tail -1 | sed 's/.*\[\([0-9]*\)%\].*/\1/'
}

vol_set(){
	amixer set $dev_default "$1%" >/dev/null
}

vol_dec(){
	amixer set $dev_default "1%-" >/dev/null
}

vol_inc(){
	amixer set $dev_default "1%+" >/dev/null
}

swap_mute(){
	echo "$devices" | while read d
	do amixer set $d toggle >/dev/null
	done
}

interactive(){
	stty -echo -icanon
	while :
	do
		printf '%d%% %s\33[K\r' "$(vol_get)" "$(list | grep '^\*' | cut -b3-)"
		ch="$(head -c1)"
		case "$ch" in
			k) vol_inc ;;
			j) vol_dec ;;
			t) swap_mute ;;
			q|) break ;;
		esac
	done
}

#dev_default=Master
#devices='Headphone Front'

# $devices may contain spaces - must read via `echo | while read`
devices=$(amixer scontrols | cut -d"'" -f2)
dev_default=$(get_active_dev)

if test -n "$VOL_DEBUG" && test "$VOL_DEBUG" != 0
then
	echo "devices (default '$dev_default'):"
	echo "$devices" | sed 's/^/  /'
fi >&2

if test $# -eq 0
then
	vol_get
elif test $# -eq 1
then
	case "$1" in
		-i) interactive ;;
		[0-9]|[0-9][0-9]|[0-9][0-9][0-9]) vol_set "$1" ;;
		t|to|tog|togg|toggl|toggle) swap_mute ;;
		l|li|lis|list) list ;;
		-) vol_dec ;;
		+) vol_inc ;;
		*) usage ;;
	esac
else
	usage
fi
