#!/bin/sh

usage(){
	echo >&2 "Usage: $0 fullscreen [filename]"
	echo >&2 "       $0 draw [filename]"
	exit 2
}

if test $# -eq 2
then
	f="$2"
elif test $# -eq 1
then
	f=$(date +%Y-%m-%d_%H:%M:%S.png)
else
	usage
fi

case "$1" in
	fullscreen)
		import -window root "$f"
		;;

	draw)
		import "$f"

		# Or:
		# g=$(xrectsel)
		# import -crop "$g" "$f"
		# import -geometry "$g" "$f"
		;;

	*)
		usage
		;;
esac

# select screen
# import -screen "$f"

# select window (excluding obscured regions)
# import "$f"

# ffcast / xrectsel - filtering etc
