#!/bin/sh

set -e

usage(){
	echo >&2 "Usage: $0 [--percent] [--state] [--raw]"
	exit 2
}

os=$(uname -s)
case "$os" in
	Darwin)
		raw(){
			pmset -g batt
		}
		default(){
			echo "$(state) $(pct)"
		}
		pct(){
			pmset -g batt | sed -n '2s/.*	\([0-9]*%\).*/\1/p'
		}
		state(){
			if pmset -g ac | grep 'No adapter' >/dev/null
			then echo batt
			else echo power
			fi
		}
		;;
	*)
		echo >&2 "$0: unknown OS \"$os\""
		exit 1
		;;
esac

case $# in
	0)
		default
		;;
	1)
		case "$1" in
			--percent) pct ;;
			--state) state ;;
			--raw) raw ;;
			*) usage ;;
		esac
		;;
	*)
		usage
		;;
esac
