#!/bin/sh

set -e

usage(){
	echo >&2 "Usage: $0 [--percent] [--state] [--raw]"
	exit 2
}

os=$(uname -s)
case "$os" in
	Darwin)
		raw(){
			pmset -g batt
		}
		pct(){
			pmset -g batt | sed -n '2s/.*	\([0-9]*%\).*/\1/p'
		}
		state(){
			if pmset -g ac | grep 'No adapter' >/dev/null
			then echo batt
			else echo power
			fi
		}
		;;
	Linux)
		raw(){
			/bin/acpi
		}
		_populate(){
			read _name _battno state pct _time _remaining <<-!
			$(raw)
			!

			state=$(echo "$state" | tr -d , | tr A-Z a-z)
			pct=$(echo "$pct" | tr -d ,)

			case "$state" in
				discharging)
					state=discharging
					;;
				charging|full)
					state=charging
					;;
				*)
					echo >&2 "$0: unknown state \"$state\""
					exit 3
					;;
			esac
		}
		pct(){
			_populate
			echo "$pct"
		}
		state(){
			_populate
			echo "$state"
		}
		;;
	*)
		echo >&2 "$0: unknown OS \"$os\""
		exit 1
		;;
esac

default(){
	echo "$(state) $(pct)"
}

case $# in
	0)
		default
		;;
	1)
		case "$1" in
			--percent) pct ;;
			--state) state ;;
			--raw) raw ;;
			*) usage ;;
		esac
		;;
	*)
		usage
		;;
esac
