#!/bin/sh

usage(){
	echo >&2 "Usage: $0 --show=active | --show=all | --kill | --chmod=..."
	exit 2
}

if test $# -eq 0
then usage
fi

chmod=
args=
kill=0
show=0
while test $# -gt 0
do
	case "$1" in
		--help)
			usage
			;;
		--show=active)
			shift
			show=1
			args='-perm +a+x'
			;;
		--show=all)
			shift
			show=1
			args=''
			;;
		--kill)
			shift
			kill=1
			;;
		--chmod=*)
			chmod=${1#--chmod=}
			shift
			;;
		*)
			usage
			;;
	esac
done

list(){
	find */ -path '*/MacOS/*' $args -type f -regex '.*/MacOS/[^/]*$' "$@"
}

indent(){
	sed 's/^/  /'
}

if test -n "$chmod"
then
	echo "chmodding"
	list | tr '\n' '\0' | xargs -0 sudo chmod "$chmod" 2>&1 | indent
fi

if test $kill -eq 1
then
	list | while read line; do
		basename=$(echo "$line" | sed 's;.*/;;')
		echo "killing $basename"
		pkill -9 "$basename" 2>&1 | indent
	done
fi

if test $show -eq 1
then list
fi
