#!/bin/sh

# -d: display
# -i: idle sleep
# -m: disk sleep
# -s: system sleep (only works on ac power)
# -u: user active (defaults to 5 sec timeout)
# -t timeout: (ignored when cmd given)
# -w pid: wait for pid (ignored when cmd given)

# see also:
# pmset displaysleep <n>
# pmset disksplaysleep <n>

usage(){
	echo >&2 "Usage: $0 [--screen] [--user] [cmd [args...]]"
	echo >&2 "  --screen: keep screen on"
	echo >&2 "  --user: user activity"
	exit 2
}

screen=false
user=false
while test $# -ne 0; do
	case "$1" in
		--screen)
			screen=true
			shift
			;;
		--user)
			user=true
			shift
			;;
		-*)
			usage
			;;
		*)
			break
			;;
	esac
done

mode=-i
$screen && mode="${mode}d"
$user && mode="${mode}u"

exec caffeinate "$mode" "$@"
