#!/bin/sh

if test $# -ne 0
then
	echo >&2 "Usage: $0"
	exit 2
fi

store=~/.dmesg-errors

last="$(cat "$store" 2>/dev/null)"
#current="$(dmesg -T | grep -E '\b(fatal|error|errors|failed|failure)\b')"
current="$(dmesg -T --level err)"

if test "$last" != "$current"
then
	echo >&2 "!!! new dmesg error: $current"
	echo "$current" > "$store"
fi
