#!/bin/bash

usage(){
	echo >&2 "Usage: $0 [-n] [-p] [-u file]"
	echo >&2 " -p: dump processes too"
	echo >&2 " -u: show update compared to file"
	echo >&2
	echo >&2 "Usage: $0 restore <file>"
	exit 2
}

echo=
if test "$1" = -n
then
	shift
	echo='echo %'
fi

window_name(){
	# $1 = path
	tmux list-windows -F '#{session_name}:#{window_index} #{window_name}' \
		| while read p rest
		do
			if test "$p" = "$1"
			then
				echo "$rest"
				break
			fi
		done
}

window_is_auto_named(){
	# $1 = path
	window_name "$1" | grep '^>' >/dev/null
}

restore(){
	windows=
	sessions=
	first=true

	case "$#" in
		0)
			cat
			;;
		1)
			if echo "$1" | grep '^-' >/dev/null
			then usage
			fi
			cat "$1"
			;;
		*)
			usage
			;;
	esac \
		| sed 's/path=//' \
		| awk '{print $1 " " $2 " " $4}' \
		| awk '!x[$1]++' \
		| while read path name wd
		do
			orig_path=$path
			path=${path%.*}
			args=(-c "$wd")
			name_arg=()
			split=false
			use_cur=false

			if ! echo "$name" | grep '^>' >/dev/null
			then
				# not just a plain shell, assume explicit name
				name="$(echo "$name" | tr _ ' ')"
				if tmux lsw -F '#W' | grep -x "$name" >/dev/null
				then
					pane=$(echo "$orig_path" | cut -d. -f2-)
					if test "$pane" -gt 0
					then
						echo "[*] already got $name, but creating a new pane ($orig_path)"
						split=true
					else
						echo "[!] already got $name, skipping" >&2
						continue
					fi
				else
					name_arg=(-n "$name")
				fi
			fi

			if test -z "$windows"
			then windows=$(tmux lsw -F '#{session_name}:#{window_index}')
			fi

			echo "[*] creating pane @ $path called \"$name\" in \`$wd\`"
			if $split || echo "$windows" | grep -Fx "$path" >/dev/null
			then
				if ! $split
				then
					if $first && test -n "$TMUX"
					then
						first=false
						echo "[*] window $path exists, and we're in tmux - using this pane"
						use_cur=true
					else
						echo "[*] window $path exists, splitting"
					fi
				fi
				if $use_cur
				then
					$echo cd "$wd"
					test -z "$echo" && echo "[>] cd \"$wd\""
				else
					$echo tmux split-window -d -t "$path" "${args[@]}"
				fi
				if test -n "$name_arg" && window_is_auto_named "$path"
				then
					$echo tmux rename-window -t "$path" "$name"
				fi
			else
				if test -z "$sessions"
				then sessions=$(tmux ls -F '#{session_name}')
				fi

				if ! echo "$sessions" | grep -Fx "${path%%:*}" >/dev/null
				then
					# can't give target (`-t "$path"`)
					$echo tmux new-session -d "${name_arg[@]}" "${args[@]}" -s "${path%%:*}"
				else
					$echo tmux new-window -d -t "$path" "${name_arg[@]}" "${args[@]}"
				fi
			fi
		done
}

dump(){
	proc=0
	update_file=
	while test $# -ne 0
	do
		if test "$1" = -p
		then proc=1
		elif test "$1" = -u
		then
			shift
			update_file="$1"
			if test -z "$update_file"
			then usage
			fi
		else usage
		fi
		shift
	done

	strip_proc(){
		sed -n '/^ *PID/q; p'
	}

	fmt_pre='#{session_name}:#{window_index}.#{pane_index} #{s/ /_/:window_name}'
	fmt_post=' cmd=#{pane_current_command} path=#{pane_current_path}'
	fmt_mid=
	if test $proc -ne 0
	then fmt_mid=' pid=#{pane_pid}'
	fi

	if test -n "$update_file"
	then
		t=/tmp/tmux-pane-cmp-$$
		trap "rm -f '$t'" EXIT

		strip_proc < "$update_file" > "$t"

		arg=
		if test $proc -ne 0
		then arg=-p
		fi

		"$0" $arg | strip_proc | diff -u "$t" -
		exit
	fi

	tmux lsp -aF "$fmt_pre$fmt_mid$fmt_post"

	if test $proc -ne 0
	then ps -e -o pid,ppid,uid,gid,state,nice,tty,command
	fi
}

case "${0##*/}" in
	tmux-pane-restore)
		restore "$@"
		;;
	*)
		if test "$1" = restore
		then
			shift
			restore "$@"
		else
			dump "$@"
		fi
		;;
esac
